.Dd July 22, 2013
.Dt NVDXJIRA 1
.Os
.Sh NAME
.Nm nvdXjira
.Nd cross-reference CVEs from the NVD with Jira
.Sh SYNOPSIS
.Nm
.Op Fl Dhlnv
.Op Fl c Ar file
.Op Fl d Ar dbfile
.Op Fl j Ar url
.Op Fl o Ar format
.Op Fl p Ar project
.Op Fl r Ar file
.Op Fl t Ar tag
.Sh DESCRIPTION
The
.Nm
utility cross-references CVEs found in a local sqlite3 copy of NIST's
National Vulerability Database with a Jira instance.
That is, for every CVE found in the database, it will look for tickets
containing the CVE identifier anywhere in the text.
For any CVEs not found in Jira,
.Nm
can create a new ticket.
.Sh OPTIONS
.Nm
supports the following options:
.Bl -tag -width p_project_
.It Fl D
Run in debug mode.
No tickets will be created.
.It Fl c Ar file
Read configuration from this file.
.It Fl d Ar dbfile
Read input from the given database file.
.It Fl h
Print a short usage statement and exit.
.It Fl j Ar url
Specify the base URL for Jira.
.It Fl l
List Jira tickets with their respective CVEs.
This is the default mode.
.It Fl n
Create new tickets for CVEs not found in Jira.
.It Fl o Ar format
Specify output format.
May be 'list' (default) or 'details'.
.It Fl p Ar project
If
.Fl n
was specified, create new tickets in this project.
.It Fl r Ar file
Read regular expressions from this file and immediately close any tickets
where the body matches.
.It Fl t Ar tag
If
.Fl n
was specified, tag new tickets with this tag/label.
.It Fl v
Be verbose.
Can be specified multiple times.
.El
.Sh DETAILS
.Nm
operates on an sqlite3 copy of NIST's National Vulnerability Database,
created using the
.Xr nvd2sqlite3 1
utility.
It will loop over all entries in the database, and, for each CVE found,
query Jira for any tickets containing the CVE identifier in its text, and
either print the ticket to CVE mappings (default) or create a new ticket
for the CVE.
.Pp
New tickets are, by default, created under the 'VULN' project, and tagged
with the 'cve' label.
.Sh CONFIGURATION
By default,
.Nm
reads its configuration from the file
.Ar /etc/nvdXjira
(if it exists).
In this file, you can specify the following keyword=value pairs:
.Bl -tag -width password_
.It database
The pathname of the database to read input from.
Overwrite using the
.Fl d
flag.
Defaults to
.Ar /var/db/cvedb/nvd.db .
.It password
The password with which to authenticate against the Jira API.
Overwrite using the
.Ar NVDXJIRA_PASSWORD
environment variable.
No default value.
.It project
The Jira project under which to create new tickets.
Overwrite using the
.Fl p
flag.
Defaults to 'VULN'.
.It reject
The pathname of a file containing regular expressions based on which to
immediately close any tickets with a matching description.
No default value.
.It url
The base URL for Jira API access.
Overwrite using the
.Fl u
flag.
No default value.
.It username
The username to authenticate as against the Jira API.
Overwrite using the
.Ar NVDXJIRA_USER
environment variable.
Defaults to
.Ar USER .
.It tag
The tag with which to label newly created tickets.
Overwrite using the
.Fl n
flag.
Defaults to 'cve'.
.El
.Sh EXAMPLES
To list all tickets for all CVEs in the database '/var/db/nvd.db'
.Bd -literal -offset indent
nvdXjira -d /var/db/nvd.db
.Ed
.Pp
To create new tickets for any CVEs found in the database but not yet in
Jira, using the 'security' project and tagging each ticket using the 'nvd'
label:
.Bd -literal -offset indent
nvdXjira -n -d /var/db/cve.db -p security -t nvd
.Ed
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr nvd2sqlite3 1 ,
.Xr sqlite3 1 ,
.Xr yvc 1
.Sh HISTORY
.Nm
was originally written by
.An Jan Schaumann
.Aq jschauma@netmeister.org
in April 2013.
